# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-16 19:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statecoin50', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='dates',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='coin',
            name='details',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
