# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-16 21:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statecoin50', '0002_auto_20170416_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='dateOwned',
            field=models.DateField(blank=True, null=True),
        ),
    ]
