# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statecoin50', '0003_coin_dateowned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='stURL',
            field=models.CharField(max_length=250),
        ),
    ]
